import "@/styles/globals.css";

import { type Metadata } from "next";
import { Montserrat } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Providers } from "@/providers";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: {
    default: "VetApp",
    template: "%s | VetApp",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pl" className={`${montserrat.variable} `}>
      <body className="bg-background font-montserrat flex min-h-screen flex-col overflow-x-hidden">
        <TRPCReactProvider>
          <NuqsAdapter>
            <Providers>
              <div className="flex h-full w-screen flex-grow flex-col">
                <Header />
                {children}
              </div>
            </Providers>
          </NuqsAdapter>
        </TRPCReactProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
